const bookmakers = [
	{ name: '10Bet' },
	{ name: '188Bet' },
	{ name: '18bet' },
	{ name: '1xBet' },
	{ name: '888sport' },
	{ name: 'bet-at-home' },
	{ name: 'bet365' },
	{ name: 'Betclic' },
	{ name: 'Betfair' },
	{ name: 'Bethard' },
	{ name: 'Betsafe' },
	{ name: 'Bettson' },
	{ name: 'BetVictor' },
	{ name: 'Betway' },
	{ name: 'BoyleSports' },
	{ name: 'bwin' },
	{ name: 'ComeOn' },
	{ name: 'Coolbet' },
	{ name: 'Expekt' },
	{ name: 'Interwetten' },
	{ name: 'Jetbull' },
	{ name: 'KTO' },
	{ name: 'Leonbets' },
	{ name: 'Marathonbet' },
	{ name: 'NordicBet' },
	{ name: 'Oddsring' },
	{ name: 'Pinnacle' },
	{ name: 'SBoBet' },
	{ name: 'Sportingbet' },
];

exports.seed = async (knex) => knex('bookmakers').del()
	.then(() => knex('bookmakers').insert(bookmakers));
